# Generated by Django 4.0.6 on 2023-06-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('jurado', models.IntegerField(verbose_name='jurado')),
                ('degustador', models.IntegerField(verbose_name='degustador')),
                ('muestra', models.IntegerField(verbose_name='muestra')),
                ('vista_limpidez', models.IntegerField(verbose_name='vista_limpidez')),
                ('vista_color', models.IntegerField(verbose_name='vista_color')),
                ('olfato_intensidad', models.IntegerField(verbose_name='olfato_intensidad')),
                ('olfato_franqueza', models.IntegerField(verbose_name='olfato_franqueza')),
                ('olfato_claridad', models.IntegerField(verbose_name='olfato_claridad')),
                ('gusto_intensidad', models.IntegerField(verbose_name='gusto_intensdad')),
                ('gusto_franqueza', models.IntegerField(verbose_name='gusto_franqueza')),
                ('gusto_calidad', models.IntegerField(verbose_name='gusto_calidad')),
                ('gusto_persistencia', models.IntegerField(verbose_name='gusto_persistencia')),
                ('apreciacion_global', models.IntegerField(verbose_name='apreciacion_global')),
                ('observaciones', models.TextField(null=True, verbose_name='Observaciones')),
            ],
        ),
    ]
